Types and operators hw
bxrxbxzx/AQA_MTS pull request #3
Opened 2023-11-21 01:46 UTC by bxrxbxzx

2023-11-24 22:35 UTC, wildpioneer requested changes

2023-11-24 22:35 UTC, wildpioneer commented on TypesAndOperators/FirstTask.cs
> +        //Задание 1. Калькулятор
Неверно созданный Pull Request - не верный target branch

2023-11-24 22:35 UTC, wildpioneer commented on TypesAndOperators/FirstTask.cs
> +                Console.WriteLine($"Ответ : {result}");
А для чего ты сразу выводишь результат? Это создает дубликаты ненужного кода.

2023-11-24 22:35 UTC, wildpioneer commented on TypesAndOperators/FirstTask.cs
> +
Лучше здесь вывести результат

2023-11-24 22:35 UTC, wildpioneer commented on TypesAndOperators/ThirdTask.cs
> +        if (Console.ReadLine("Осень")
Комментарии и лишний код не оставляют в Pull Request-е
Скобки не хватает - раз
Это не работает - два

2023-11-25 08:38 UTC, bxrxbxzx commented on TypesAndOperators/ThirdTask.cs
> +        if (Console.ReadLine("Осень")
Закомитил код для того, что бы узнать, вдруг Вы сможете подсказать как htfkbpjdfnm  с dictionary.
Ниже код, который работает. На счет скобки- ide ничего не подсветила.
![image](https://github.com/bxrxbxzx/AQA_MTS/assets/48456459/40aad995-b2fb-4862-abb4-6cfcd24abc8e)
Код и комментарии уберу.

2023-11-25 08:40 UTC, bxrxbxzx commented on TypesAndOperators/FirstTask.cs
> +
после break?

2023-11-25 08:44 UTC, bxrxbxzx commented on TypesAndOperators/FirstTask.cs
> +                Console.WriteLine($"Ответ : {result}");
убрал лишние строки, оставил одну. Спасибо за подсказку.

2023-11-25 08:57 UTC, bxrxbxzx commented on TypesAndOperators/FirstTask.cs
> +
так и не понял, как корректно разместить строчку по выводу- если после брейк- она дисейблится. Если нет перед блоком с if- нет вывода результата. Буду разбираться дальше.

2023-11-25 19:39 UTC, bxrxbxzx commented on TypesAndOperators/FirstTask.cs
> +        //Задание 1. Калькулятор
Простите, не могли бы объяснить? Я же запрашиваю мерж из ветки с домашней работой в мастер? Разве не так? Т. е., сейчас у меня все эти 4 задания в ветке TypesAndOperators_HW, разве нет? 
![image](https://github.com/bxrxbxzx/AQA_MTS/assets/48456459/d88269de-44d3-4eb9-9d62-e2c4ffe45e56)

2023-11-25 19:59 UTC, bxrxbxzx commented on TypesAndOperators/FirstTask.cs
> +
разобрался. Перенес вывод результата на 48 строку. В новом коммите

2023-11-27 17:02 UTC, wildpioneer commented on TypesAndOperators/FirstTask.cs
> +        //Задание 1. Калькулятор
Нет. Ты должен запрашивать merge на бранч с классной работой, т.е. в твоем случае должно быть
TypesAndOperators - классная работа
TypesAndOperators_HW - домашняя работа
и PR создавать на мерж из TypesAndOperators_HW -> TypesAndOperators

2024-01-29 09:25 UTC, wildpioneer commented
Проверено

2024-01-29 09:25 UTC, wildpioneer commented
По какой-то причине не могу закрыт данный бранч - закрой его сам

2024-02-05 18:34 UTC, closed without merging